stages:
  - deploy

variables:
  DEPLOYMENT_ROOT: 'C:/Deployment'
  ErrorActionPreference: STOP

deploy_test:
  stage: deploy
  script:
    - echo 'Deploying to Test'
    - echo 'Creating folder for Test'
    - New-Item -Path $env:DEPLOYMENT_ROOT -Name "test" -ItemType "directory" -Force
    - echo 'Copying files to deployment folder'
    - $target = Join-Path $env:DEPLOYMENT_ROOT "test/" 
    - $ph = $env:CI_PROJECT_PATH
    - echo $ph
    - Copy-Item $env:CI_PROJECT_PATH -Destination $target -Recurse -Container -Force
    - echo 'Files copied to $target'
  only:
    - test
  tags:
    - test

deploy_acc:
  stage: deploy
  script:
    - echo "Deploying to Acc"
  only:
    - acc
  tags:
    - acc

deploy_prod:
  stage: deploy
  script:
    - echo "Deploying to Prod"
  only:
    - prod
  tags:
    - prod