stages:
  - deploy

variables:
  DEPLOYMENT_ROOT: 'C:\\Deployed\\test'
  ErrorActionPreference: STOP

deploy_test:
  stage: deploy
  script:
    - echo 'Deploying to Test'
    - echo 'Copying files from $env:CI_PROJECT_DIR'
    - echo $env:CI_PROJECT_DIR
    - Copy-Item "C:/test/" -Destination "C:/Deployed/test" -Force -Recurse -Container
    - echo 'Files copied to $env:DEPLOYMENT_ROOT\test'
  only:
    - test
  tags:
    - test

deploy_acc:
  stage: deploy
  script:
    - echo "Deploying to Acc"
  only:
    - acc
  tags:
    - acc

deploy_prod:
  stage: deploy
  script:
    - echo "Deploying to Prod"
  only:
    - prod
  tags:
    - prod