stages:
  - deploy

variables:
  DEPLOYMENT_ROOT: 'C:/Deployment'
  ErrorActionPreference: STOP

deploy_test:
  stage: deploy
  variables:
    envname: 'test'
  script:
    - echo 'Deploying to Test'
    - echo 'Creating folder for Test'
    - New-Item -Path $env:DEPLOYMENT_ROOT -Name $env:envname -ItemType "directory" -Force
    - echo 'Copying files to deployment folder'
    - $target = Join-Path $env:DEPLOYMENT_ROOT $env:envname
    - $source = Join-Path $env:CI_PROJECT_DIR "*" 
    - Copy-Item $source -Destination $target -Recurse -Container -Force
    - echo 'Files copied to $target'
  only:
    - test
  tags:
    - test

deploy_acc:
  stage: deploy
  script:
    - echo "Deploying to Acc"
  only:
    - acc
  tags:
    - acc

deploy_prod:
  stage: deploy
  script:
    - echo "Deploying to Prod"
  only:
    - prod
  tags:
    - prod