stages:
  - test
  - build

test:
  stage: test
  script: echo "Running tests"
  tags: 
    - acc
    - test

build:
  stage: build
  script: |
    echo "Building the app"
  tags: 
    - acc
    - test