stages:
  - test
  - build

test:
  stage: test
  script: echo "Running tests"
  tags: 
    - acc
    - test

build:
  stage: build
  script: |
    echo "Building the app"
    echo "Creating testfile"
    echo testfile  > testfile.txt
  tags: 
    - acc
    - test