stages:
  - deploy

deploy_test:
  stage: deploy
  script:
    - echo "Deploying to Test"
  only:
    - test
  tags:
    - test

deploy_acc:
  stage: deploy
  script:
    - echo "Deploying to Acc"
  only:
    - acc
  tags:
    - acc

deploy_prod:
  stage: deploy
  script:
    - echo "Deploying to Prod"
  only:
    - prod
  tags:
    - prod